export type EmploymentData = {
  firstName: string;
  secondName: string;
  thirdName: string;
  forthName: string;
  genderId: number;
  birthDate: any;
  nationalityId: number;
  maritalStatusId: number;
  religionId: number;
  phone: string;
  mobile: string;
  fileId: string;
  employeeTypeId: number;
  currentStatusId: number;
  birthPlace: string;
  nationalAddress: string;
  zipcode: string;
  countryJoiningDate: any;
  recordId: string;
  nationalId: string;
  releaseDate: any;
  releasePlace: string;
  municipalityJoiningDate: any;
  retirementDate:any;
};
